### ISSUE TITLE
Can't use feature when using the last checkbox of commit list.

### ISSUE THREAD

**Issue by acetrand** [hengun348/GitHub-compare-helper#3]
### Test steps
1. Go to the list of commits
2. Tick a checkbox
3. Then, tick the last checkbox at the page
4. Click the button `[Generate compare url]`
### Expected result

I should navigate to the compare url of the range I selected.
### Actual result

Nothing happens.

**Comment by acetrand** [comment]
Based on another discussion it sounded like you consider using the last checkbox is an edge case and therefor will not try to solve the issue. However, I at least would expect some sort of feedback or explanation why I can't use it.

Crazy thought, maybe you could not render a checkbox at all for the last commit?

**Comment by hengun348** [comment]
I want ahead with the crazy though and do not display the last checkbox. Have at least some explanation for why it is hidden in the description for the plugin in chrome store.
